## Numpy

In [15]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[1,1,1,1]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 1, 1, 1]])

In [10]:
a.ndim #dimension of array

2

In [11]:
a.itemsize #size of int

4

In [12]:
a.dtype

dtype('int32')

In [17]:
a.size #no of digits in array

12

In [110]:
a.max() 
a.min()
a.mean()
a.sum()
a.shape #no rows and columns
np.sqrt(a) #suaare root of all digits
np.std(a) #standard deviation of all digits


2.494438257849294

In [44]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
b = np.arange(1,49)
b.resize(8,6) #resize the array shape
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48]])

In [92]:
b[2,3] #indexing


16

In [95]:
b.ravel() #make array in one dimensional

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [101]:
b.sum(axis = 0)      #sum of all digits from up to down all columns

array([176, 184, 192, 200, 208, 216])

In [103]:
b.sum(axis = 1)      #sum of all digits from left to right all rows

array([ 21,  57,  93, 129, 165, 201, 237, 273])

In [88]:
np.linspace(1,10,20) #(start, end, no of digits we want)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [115]:
arr1 = np.array([
    [1,2],
    [5,6]
])
arr2 = np.array([
    [3,4],
    [7,8]
])
arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1.dot(arr2)


array([[17, 20],
       [57, 68]])