In [ ]:
import numpy as np

In [ ]:
n = np.array([10, 20, 30, 40]) #single dimensional array
n

array([10, 20, 30, 40])

In [ ]:
n = np.array([[1, 2, 3, 4],[5, 6, 7, 8]]) #multidimensional array
n

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
n = np.zeros((5,3)) #zeros array (row, col)
n

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
n = np.full((5,5), 10) #with specific number (row, col), number
n

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
n = np.arange(10,25) #number range in array (start, end)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
n = np.arange(10,100,5) #number range in array (start, end, gap)
n

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
n = np.random.randint(10, 100, 5) # number randomly in array (start, end, number)
n

array([90, 97, 72, 58, 51])

In [ ]:
n = np.zeros((5,10))
n.shape #old shape
n.shape = (10,5) #change shape
n.shape #new shape

(10, 5)

In [ ]:
# join 2 numpy array (vstack())
n1 = np.array([1,2,3,4])
n2 = np.array([1,2,3,4])
np.vstack((n1,n2))


array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
# join 2 numpy array (hstack())
n1 = np.array([1,2,3,4])
n2 = np.array([1,2,3,4])
np.hstack((n1,n2))

array([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
# join 2 numpy array (column_stack())
n1 = np.array([1,2,3,4])
n2 = np.array([1,2,3,4])
np.column_stack((n1,n2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
# intersection & Difference 
n1 = np.array([1,3,4,8,2,7])
n2 = np.array([8,1,5,3,6])
np.intersect1d(n1,n2) #return the common elements between two arrays

array([1, 3, 8])

In [ ]:
n1 = np.array([1,3,4,8,2,7])
n2 = np.array([8,1,5,3,6])
np.setdiff1d(n1,n2) # return the unique elements in array n1

n1 = np.array([1,3,4,8,2,7])
n2 = np.array([8,1,5,3,6])
np.setdiff1d(n2,n1) # return the unique elements in array n2


array([5, 6])

In [ ]:
# addition/sum of two arrays
n1 = np.array([1,3,4,8,2])
n2 = np.array([8,1,5,3,6])
np.sum([n1,n2]) # sum of two arrays

41

In [ ]:
n1 = np.array([1,3,4,8,2])
n2 = np.array([8,1,5,3,6])
np.sum([n1,n2], axis=0) # sum of each elements between two arrays (axis=0) with respect to column 

array([ 9,  4,  9, 11,  8])

In [ ]:
n1 = np.array([1,3,4,8,2])
n2 = np.array([8,1,5,3,6])
np.sum([n1,n2], axis=1) # sum of two array individually (axis=1) with respect to row 

array([18, 23])

In [ ]:
# basic operation with numpy array
n1 = np.array([1,3,4,8,2])
n1 = n1 + 1 #basic addition same as for (-, *, /)
n1

array([2, 4, 5, 9, 3])

In [ ]:
# mean, median, std in numpy array
n1 = np.array([1,3,4,8,2])
np.mean(n1) #mean

3.6

In [ ]:
n1 = np.array([1,3,4,8,2])
np.median(n1) #median

3.0

In [ ]:
n1 = np.array([1,3,4,8,2])
np.std(n1) #standard deviation

2.4166091947189146

In [ ]:
# save and load numpy array
n1 = np.array([1,3,4,8,2])
np.save('my_save_n1', n1)

In [ ]:
np.load('my_save_n1.npy') #.npy means numpy array

array([1, 3, 4, 8, 2])